version: '3.8'

services:
  flask:
    build: ./backend
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    working_dir: /usr/src/app/backend
    depends_on: 
        - dbPostgres
    command: flask run --host=0.0.0.0

  dbPostgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
        - 5432:5432
    env_file:
      - .env


  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "${DB_MANAGER_PORT}:8080"
    depends_on:
      - dbPostgres
