"""create all entitys

Revision ID: 1873d3eb0db6
Revises: 
Create Date: 2022-01-24 11:55:49.268620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1873d3eb0db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('remove_date', sa.Date(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_create_date'), 'certificates', ['create_date'], unique=False)
    op.create_index(op.f('ix_certificates_remove_date'), 'certificates', ['remove_date'], unique=False)
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('respondibilities', sa.String(length=300), nullable=True),
    sa.Column('school', sa.String(length=150), nullable=False),
    sa.Column('school_graduation', sa.String(length=5), nullable=False),
    sa.Column('MPT_entrance', sa.String(length=5), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('remove_date', sa.Date(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristics_create_date'), 'characteristics', ['create_date'], unique=False)
    op.create_index(op.f('ix_characteristics_remove_date'), 'characteristics', ['remove_date'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment', sa.String(length=300), nullable=False),
    sa.Column('semestr', sa.String(length=45), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_create_date'), 'payments', ['create_date'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specialitys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('surname', sa.String(length=45), nullable=True),
    sa.Column('secondname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('specialitys')
    op.drop_table('roles')
    op.drop_index(op.f('ix_payments_create_date'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('groups')
    op.drop_index(op.f('ix_characteristics_remove_date'), table_name='characteristics')
    op.drop_index(op.f('ix_characteristics_create_date'), table_name='characteristics')
    op.drop_table('characteristics')
    op.drop_index(op.f('ix_certificates_remove_date'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_create_date'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
