"""create base structure

Revision ID: 60c0e1e6134b
Revises: 
Create Date: 2022-03-18 12:54:05.054470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c0e1e6134b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('specialitys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialitys')),
    sa.UniqueConstraint('code', name=op.f('uq_specialitys_code')),
    sa.UniqueConstraint('name', name=op.f('uq_specialitys_name'))
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses'))
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialitys.id'], name=op.f('fk_groups_speciality_id_specialitys'), onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('surname', sa.String(length=45), nullable=True),
    sa.Column('secondname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_users_group_id_groups'), onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('remove_date', sa.Date(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_certificates_status_id_statuses'), onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certificates_user_id_users'), onupdate='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_index(op.f('ix_certificates_create_date'), 'certificates', ['create_date'], unique=False)
    op.create_index(op.f('ix_certificates_remove_date'), 'certificates', ['remove_date'], unique=False)
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('respondibilities', sa.String(length=300), nullable=True),
    sa.Column('school', sa.String(length=150), nullable=False),
    sa.Column('school_graduation', sa.String(length=5), nullable=False),
    sa.Column('MPT_entrance', sa.String(length=5), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('remove_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_characteristics_status_id_statuses'), onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characteristics_user_id_users'), onupdate='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characteristics'))
    )
    op.create_index(op.f('ix_characteristics_create_date'), 'characteristics', ['create_date'], unique=False)
    op.create_index(op.f('ix_characteristics_remove_date'), 'characteristics', ['remove_date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment', sa.String(length=300), nullable=False),
    sa.Column('semestr', sa.String(length=45), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), onupdate='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_create_date'), 'payments', ['create_date'], unique=False)
    op.create_table('users_roles',
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_roles_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_index(op.f('ix_payments_create_date'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_characteristics_remove_date'), table_name='characteristics')
    op.drop_index(op.f('ix_characteristics_create_date'), table_name='characteristics')
    op.drop_table('characteristics')
    op.drop_index(op.f('ix_certificates_remove_date'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_create_date'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('statuses')
    op.drop_table('specialitys')
    op.drop_table('roles')
    # ### end Alembic commands ###
