"""add status entity

Revision ID: 8a86d2a0d57e
Revises: b6ebf273e608
Create Date: 2022-03-02 15:28:05.663386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a86d2a0d57e'
down_revision = 'b6ebf273e608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses'))
    )
    op.add_column('certificates', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_certificates_status_id_statuses'), 'certificates', 'statuses', ['status_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.add_column('characteristics', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_characteristics_status_id_statuses'), 'characteristics', 'statuses', ['status_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_characteristics_status_id_statuses'), 'characteristics', type_='foreignkey')
    op.drop_column('characteristics', 'status_id')
    op.drop_constraint(op.f('fk_certificates_status_id_statuses'), 'certificates', type_='foreignkey')
    op.drop_column('certificates', 'status_id')
    op.drop_table('statuses')
    # ### end Alembic commands ###
